services:
  db:
    image: postgres:18.3
    user: postgres
    restart: always
    environment:
      - POSTGRES_DB=fuma_comment
      - POSTGRES_PASSWORD=secret
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - 5432:5432

volumes:
  pgdata:
